[Variables]
Bar_Opacity=ff
Bar_Opacity_Percent=100
Bar_Width =1100
Bar_Height =50
Bar_OffsetX =410
Bar_OffsetY =0

Color_Scheme1 =101010
Color_Scheme2 =FFFFFF
Color_Scheme3 =FF6D70
Color_Scheme4 =101010

Font_Face=SF Pro Text
Font_Size=11
Font_Weight = 600

SubSkinPadding = 20
SubSkinCornerRadius = 20

SliderKnobRadius = 12
SliderHeight = 3

DefaultAddedModules=volume,workspacemanager,time,battery,wifi,weather

